language: generic

sudo: true

before_script:
  - sudo add-apt-repository --yes ppa:git-core/ppa
  - sudo apt-get update --yes
  - sudo apt-get install --yes git || sudo apt-get upgrade --yes git

script:
  - ./test/run-tests
